const responseObj = {
  hello: "Hey ! How are you doing ?",
  hey: "Hey! What's Up",
  thanks: "With pleasure",
  bonjour : "Bonjour! Comment je peux t'aider :-) ?",
  merci : "Avec beaucoup de plaisir :-)",
  info : "je suis là pour te donner des informations sur la culture marocaine (Cuisine ; Habits ; Musique ; Produits Cosmétiques ; Personnes Historiques ; ... ) Merhba :-) ",
  chatbot : "(1)Cuisine (2)Habits (3)Musique (4)Personnes Historiques (5)Beauté (6)Places à Visiter (7)Outils de Cuisine",
  today: new Date().toDateString(),
  time: new Date().toLocaleTimeString(),

  // Général :
  Maroc : "Le Maroc est un pays très diversifié en termes de cultures en raison de son histoire complexe et de sa position géographique à la croisée des chemins entre l'Afrique, l'Europe et le Moyen-Orient.",
  1 : "-couscous -tajine -pastilla -harira -zaalouk -mrouzia -...",
  2 : "-caftan -selham -jabador -tarbouche -sfifa -takchita -...",
  3 : "-musique_aissawa -ahwach -aita -ahidous -musique_chaabi -musique_raï -...",
  4 : "-Moulay_Ismail -Tahar_Ben_Jelloun -Fatima_AlFihri -Ahmed_Baba -Ibn_Battuta -Fatima_Mernissi -...",
  5 : "-argan -eau_de_rose -henné -savon_noir -ghassoul -rose_Damas -...",
  6 : "-Jemaa_el_Fna -Place_Moulay_Hassan -Tombeaux_saadiens -Place_Mohammed_V -Tour_Hassan -Kasbah_Ait_Benhaddou -...",
  7 : "-couscoussier -couteau -houf -cendrier -tamis -moule -...",

  // Les Cultures :
  amazighe : "Les Amazighs sont l'un des groupes ethniques les plus anciens du Maroc, avec une histoire qui remonte à des milliers d'années. Les Berbères ont leur propre langue, leur propre musique, leurs propres traditions et leur propre cuisine.",
  berbère : "Les Amazighs sont l'un des groupes ethniques les plus anciens du Maroc, avec une histoire qui remonte à des milliers d'années. Les Berbères ont leur propre langue, leur propre musique, leurs propres traditions et leur propre cuisine.",
  arabe : "Les Arabes ont influencé la culture marocaine pendant des siècles, apportant avec eux leur religion, leur langue et leur cuisine. L'arabe est la langue officielle du Maroc et l'islam est la religion d'État.",
  juive : "La communauté juive marocaine a une histoire riche et complexe qui remonte à des siècles. Les Juifs ont apporté leur propre langue, leur propre cuisine et leurs propres traditions religieuses, qui ont toutes été intégrées à la culture marocaine.",
  andalouse : "L'Andalousie était une région d'Espagne qui a été sous domination musulmane pendant plusieurs siècles, et cette influence a été ressentie jusqu'au Maroc. La musique andalouse, la calligraphie et l'architecture sont toutes des éléments importants de la culture marocaine.",
  saharienne : "Les régions du sud du Maroc ont leur propre culture unique en raison de leur emplacement dans le désert du Sahara. Les Berbères du Sahara ont leur propre musique, leur propre artisanat et leur propre mode de vie traditionnel.",
  gnaoua : "Les Gnaouas sont un groupe ethnique qui a des racines en Afrique de l'Ouest et qui s'est installé au Maroc il y a des siècles. Ils ont apporté avec eux leur propre musique, leur propre danse et leur propre religion, qui est basée sur un mélange de l'islam et des religions africaines traditionnelles.",
  oasis : "Les oasis sont des zones fertiles dans le désert qui ont leur propre culture unique en raison de leur isolation géographique. Les habitants des oasis ont leur propre musique, leur propre cuisine et leur propre mode de vie traditionnel, qui est centré sur l'agriculture et l'irrigation.",
  nomades : "Les nomades sont des tribus qui voyagent à travers le désert avec leurs troupeaux de chameaux ou de moutons. Ils ont leur propre musique, leur propre artisanat et leur propre mode de vie traditionnel, qui est centré sur l'élevage et la migration saisonnière.",
  moderne : "Le Maroc est un pays en développement qui connaît une croissance économique rapide, ce qui a conduit à l'émergence d'une culture urbaine moderne. Les jeunes Marocains s'inspirent des cultures étrangères et créent leur propre mode de vie, leur propre musique et leur propre style de mode.",

  Amazigh: "The Amazighs are one of the oldest ethnic groups in Morocco, with a history dating back thousands of years. The Berbers have their own language, music, traditions, and cuisine.",
  Berber: "The Amazighs are one of the oldest ethnic groups in Morocco, with a history dating back thousands of years. The Berbers have their own language, music, traditions, and cuisine.",
  Arabic: "Arabs have influenced Moroccan culture for centuries, bringing with them their religion, language, and cuisine. Arabic is the official language of Morocco and Islam is the state religion.",
  Jewish: "The Moroccan Jewish community has a rich and complex history dating back centuries. Jews have brought their own language, cuisine, and religious traditions, all of which have been integrated into Moroccan culture.",
  Andalusian: "Andalusia was a region in Spain that was under Muslim rule for several centuries, and this influence was felt all the way to Morocco. Andalusian music, calligraphy, and architecture are all important elements of Moroccan culture.",
  Saharan: "The southern regions of Morocco have their own unique culture due to their location in the Sahara desert. Saharan Berbers have their own music, crafts, and traditional way of life.",
  Gnaoua: "The Gnaouas are an ethnic group with roots in West Africa who settled in Morocco centuries ago. They brought with them their own music, dance, and religion, which is based on a blend of Islam and traditional African religions.",
  oasis_eng: "Oases are fertile areas in the desert that have their own unique culture due to their geographical isolation. Oasis inhabitants have their own music, cuisine, and traditional way of life centered around agriculture and irrigation.",
  Nomads: "Nomads are tribes that travel through the desert with their herds of camels or sheep. They have their own music, crafts, and traditional way of life centered around herding and seasonal migration.",
  Modern: "Morocco is a developing country experiencing rapid economic growth, which has led to the emergence of modern urban culture. Young Moroccans draw inspiration from foreign cultures and create their own lifestyle, music, and fashion style.",

  // Cuisine :
  couscous : "un plat de semoule cuit à la vapeur accompagné de légumes, de viande et de harissa.",
  tajine : "un plat mijoté dans un plat en terre cuite en forme de cône, avec des légumes, de la viande ou du poisson et des épices.",
  pastilla : "une tourte feuilletée farcie de viande hachée, d'amandes et d'épices.",
  harira : "une soupe épaisse à base de tomates, de lentilles, de pois chiches, de viande et d'épices, souvent servie pendant le mois sacré de Ramadan.",
  zaalouk : "une salade de légumes grillés comme les aubergines et les poivrons avec de l'ail, de l'huile d'olive et des épices.",
  mrouzia : "un plat sucré-salé de viande d'agneau mijotée dans une sauce de miel, d'épices et d'amandes.  hat's Up",
  briouats : "des feuilletés farcis de viande hachée, de fromage ou de légumes et frit",
  kefta : "des boulettes de viande hachée assaisonnées d'oignons, de persil et d'épices.", 
  tanjia : "un plat mijoté de viande d'agneau marinée dans des épices et cuit lentement dans un pot en terre cuite.",
  sfenj : "des beignets marocains frits en forme de beignet.",
  rfissa : "un plat de poulet mijoté avec des lentilles, des oignons caramélisés, des épices et des feuilles de msemen (crêpes marocaines).",
  seffa : "une salade de vermicelles sucrée et épicée, garnie d'amandes grillées, de cannelle et de sucre en poudre.",
  bissara : "une soupe de fèves blanches épicée, servie chaude avec de l'huile d'olive et du cumin.",
  taktouka : "une salade de poivrons grillés et de tomates, mélangés avec de l'ail, de l'huile d'olive et des épices.",
  zitoune_beldi : "des olives vertes marinées dans de l'huile d'olive, du citron et des épices, souvent servies comme entrée.",
  khobz : "du pain marocain traditionnel, souvent cuit dans un four en terre cuite.",
  baghrir : "des crêpes marocaines légères et moelleuses, servies avec du miel ou de l'huile d'olive.",
  makouda : "des galettes de pommes de terre frites, servies avec de la harissa ou une sauce tomate épicée.",
  msemen : "une crêpe marocaine en couches, souvent servie pour le petit-déjeuner ou comme accompagnement à un tajine.",
  rghaif : "une sorte de pain feuilleté et croustillant, souvent fourré avec de la viande hachée, des herbes et des épices.",
  chermoula : "une marinade épicée à base de coriandre, de persil, d'ail, de citron et d'huile d'olive, souvent utilisée pour mariner du poisson ou de la viande.",
  harissa : "une pâte de piment rouge, d'ail et d'épices, utilisée pour donner du piquant à de nombreux plats marocains.",
  mhancha : "un gâteau marocain en forme de serpent, souvent farci d'amandes, de miel et de cannelle.",
  atay : "Le thé marocain est préparé avec du thé vert chinois, du sucre et de la menthe fraîche, et est souvent servi avec des pâtisseries marocaines",
  sellou : "un dessert traditionnel à base d'amandes, de sésame, de farine grillée, de miel et d'épices.",

  couscous_eng: "a steamed semolina dish served with vegetables, meat, and harissa.",
  tajine_eng: "a slow-cooked dish in a cone-shaped clay pot, with vegetables, meat or fish, and spices.",
  pastilla_eng: "a puff pastry pie filled with minced meat, almonds, and spices.",
  harira_eng: "a thick soup made with tomatoes, lentils, chickpeas, meat, and spices, often served during the holy month of Ramadan.",
  zaalouk_eng: "a salad of grilled vegetables like eggplants and peppers with garlic, olive oil, and spices.",
  mrouzia_eng: "a sweet and savory dish of lamb stewed in a sauce of honey, spices, and almonds.",
  briouats_eng: "filled pastries with minced meat, cheese, or vegetables and fried.",
  kefta_eng: "seasoned minced meatballs with onions, parsley, and spices.",
  tanjia_eng: "a slow-cooked dish of lamb marinated in spices and cooked slowly in a clay pot.",
  sfenj_eng: "Moroccan fried donuts in a donut shape.",
  rfissa_eng: "a chicken stew with lentils, caramelized onions, spices, and msemen leaves (Moroccan pancakes).",
  seffa_eng: "a sweet and spicy vermicelli salad, topped with grilled almonds, cinnamon, and powdered sugar.",
  bissara_eng: "a spicy white bean soup, served hot with olive oil and cumin.",
  taktouka_eng: "a salad of grilled peppers and tomatoes, mixed with garlic, olive oil, and spices.",
  zitoune_beldi_eng: "green olives marinated in olive oil, lemon, and spices, often served as an appetizer.",
  khobz_eng: "traditional Moroccan bread, often baked in a clay oven.",
  baghrir_eng: "light and fluffy Moroccan pancakes, served with honey or olive oil.",
  makouda_eng: "fried potato cakes, served with harissa or spicy tomato sauce.",
  msemen_eng: "a layered Moroccan pancake, often served for breakfast or as an accompaniment to a tajine.",
  rghaif_eng: "a type of crispy, flaky bread, often filled with minced meat, herbs, and spices.",
  chermoula_eng: "a spicy marinade made with coriander, parsley, garlic, lemon, and olive oil, often used to marinate fish or meat.",
  harissa_eng: "a paste made from red chili peppers, garlic, and spices, used to add heat to many Moroccan dishes.",
  mhancha_eng: "a Moroccan cake in the shape of a snake, often filled with almonds, honey, and cinnamon.",
  atay_eng: "Moroccan tea is prepared with Chinese green tea, sugar, and fresh mint, and is often served with Moroccan pastries.",
  sellou_eng: "a traditional dessert made with almonds, sesame seeds, roasted flour, honey, and spices.",

  // Habits :
  djellaba : "C'est une longue robe ample avec une capuche, portée par les hommes et les femmes dans tout le Maroc. La djellaba est souvent en laine pour les mois d'hiver, mais elle peut aussi être en coton léger pour l'été.",
  caftan : "Le caftan est une robe longue et ample qui est souvent portée pour les occasions spéciales comme les mariages et les fêtes. Le caftan marocain est généralement orné de broderies, de perles et de motifs colorés.",
  jabador : "Le jabador est un ensemble composé d'une veste et d'un pantalon large porté par les hommes dans tout le Maroc. La veste peut être décorée de broderies et de motifs traditionnels.",
  takchita : "La takchita est une tenue traditionnelle pour les femmes portée lors des mariages et autres événements formels. Elle est composée d'une robe longue et ample, avec une seconde robe plus serrée en dessous, ainsi qu'un voile qui peut être porté sur la tête.",
  gandoura : "La gandoura est une robe longue portée par les hommes et les femmes dans le sud du Maroc. Elle est souvent en coton léger et décorée de broderies.",
  chéchia : "La chéchia est un couvre-chef traditionnel pour les hommes au Maroc. Elle est généralement en laine et peut être de différentes couleurs.",
  sarouel : "Cette pièce vestimentaire est également portée par les hommes et les femmes, mais elle est plus populaire chez les hommes. Il s'agit d'un pantalon ample qui descend jusqu'aux chevilles et qui est souvent porté avec une djellaba ou un gilet.",
  burnous : "Cette cape traditionnelle est portée par les hommes et les femmes dans tout le Maroc, mais elle est plus répandue dans les régions du Rif et de l'Atlas. Le burnous est en laine et peut être orné de motifs géométriques ou floraux.",
  selham : "Cette cape traditionnelle est portée par les femmes dans certaines régions du Maroc, notamment dans la région de Fès. Le selham est en laine et peut être orné de motifs floraux ou géométriques.",
  tarbouche : "Ce couvre-chef traditionnel est porté par les hommes lors d'occasions formelles. Le tarbouche est souvent en velours rouge et peut être orné d'un pompon en soie.",
  babouches : "Ces chaussures traditionnelles sont portées par les hommes et les femmes dans tout le Maroc. Les babouches sont souvent en cuir et peuvent être décorées de broderies ou de motifs géométriques.",
  sarouel_harem : "Cette tenue est composée d'un pantalon ample qui descend jusqu'aux chevilles et qui est souvent porté avec une tunique ou un gilet. Le sarouel harem est souvent en coton léger et peut être décoré de broderies ou de motifs.",
  haïk : "c'est une longue pièce d'étoffe en coton ou en laine portée par les femmes pour couvrir tout leur corps, y compris la tête et le visage.",
  tagelmust : "c'est un turban en coton que les hommes portent pour se protéger du soleil et du vent. Il est généralement de couleur indigo et peut être noué de différentes manières en fonction des tribus.",
  djellaba_saharienne : "c'est une version plus légère et plus longue de la djellaba traditionnelle marocaine, fabriquée en tissu léger pour mieux résister à la chaleur du désert. La djellaba saharienne est souvent ornée de broderies complexes.",
  tchachia : "c'est une coiffe rouge en laine portée par les hommes. Elle est souvent décorée de pompons et de broderies.",
  melhfa : "c'est une pièce d'étoffe en coton ou en laine qui est portée par les femmes pour se couvrir tout le corps. Elle peut être nouée de différentes manières pour former une robe ou une jupe.",
  jebba : "C'est une robe longue portée par les femmes juives marocaines. La jebba est souvent en soie et est brodée avec des motifs floraux et géométriques.",
  tunique : "Les hommes juifs marocains portaient souvent une tunique blanche ou bleue appelée gandora, qui était souvent ornée de broderies.",
  tichal : "Les femmes juives marocaines portaient souvent un foulard appelé tichal qui couvrait leur tête et leurs épaules.",
  sfifa : "C'est une ceinture tissée à la main, souvent portée avec une djellaba ou une gandoura.",

  djellaba_eng: "It is a long, loose robe with a hood, worn by both men and women throughout Morocco. The djellaba is often made of wool for the winter months, but can also be made of lightweight cotton for the summer.",
  caftan_eng: "The caftan is a long, loose robe often worn for special occasions like weddings and parties. The Moroccan caftan is typically decorated with embroidery, beads, and colorful patterns.",
  jabador_eng: "The jabador is a set consisting of a jacket and wide pants worn by men throughout Morocco. The jacket may be decorated with traditional embroidery and motifs.",
  takchita_eng: "The takchita is a traditional outfit for women worn during weddings and other formal events. It consists of a long, loose dress with a second, tighter dress underneath, as well as a veil that may be worn on the head.",
  gandoura_eng: "The gandoura is a long robe worn by men and women in southern Morocco. It is often made of lightweight cotton and decorated with embroidery.",
  chéchia_eng: "The chéchia is a traditional head covering for men in Morocco. It is typically made of wool and can be of different colors.",
  sarouel_eng: "This article of clothing is also worn by both men and women, but is more popular among men. It is a loose-fitting pants that extend to the ankles and is often worn with a djellaba or vest.",
  burnous_eng: "This traditional cape is worn by both men and women throughout Morocco, but is more common in the Rif and Atlas regions. The burnous is made of wool and may be decorated with geometric or floral patterns.",
  selham_eng: "This traditional cape is worn by women in certain regions of Morocco, particularly in the Fes region. The selham is made of wool and may be decorated with floral or geometric patterns.",
  tarbouche_eng: "This traditional head covering is worn by men during formal occasions. The tarbouche is often made of red velvet and may be adorned with a silk tassel.",
  babouches_eng: "These traditional shoes are worn by both men and women throughout Morocco. Babouches are often made of leather and may be decorated with embroidery or geometric patterns.",
  sarouel_harem_eng: "This outfit consists of loose-fitting pants that extend to the ankles and is often worn with a tunic or vest. The harem-style sarouel is often made of lightweight cotton and may be decorated with embroidery or patterns.",
  haïk_eng: "It is a long piece of cloth made of cotton or wool worn by women to cover their entire body, including their head and face.",
  tagelmust_eng: "It is a cotton turban worn by men to protect themselves from the sun and wind. It is usually indigo in color and can be tied in different ways depending on the tribe.",
  djellaba_saharienne_eng: "It is a lighter and longer version of the traditional Moroccan djellaba, made of lightweight fabric to better withstand the heat of the desert. The Saharan djellaba is often adorned with intricate embroidery.",
  tchachia_eng: "It is a red woolen head covering worn by men. It is often decorated with tassels and embroidery.",
  melhfa_eng: "It is a piece of cloth made of cotton or wool that is worn by women to cover their entire body. It can be tied in different ways to form a dress or skirt.",
  jebba_eng: "It is a long dress worn by Moroccan Jewish women. The jebba is often made of silk and is embroidered with floral and geometric motifs.",

  // Musique :
  musique_gnawa : "Originaire du Sahara marocain, la musique Gnawa est souvent associée à des cérémonies religieuses. Elle est jouée avec des instruments tels que le guembri, une sorte de luth à trois cordes, et le krakebs, des cymbales en métal.",
  musique_chaabi : "Populaire dans les villes du Maroc, la musique chaâbi est souvent jouée lors de mariages et de fêtes. Elle est caractérisée par des paroles poétiques en darija, le dialecte marocain, et est souvent accompagnée de instruments tels que la mandoline, le violon et le banjo.",
  ahwach : "Ahwach est une forme de musique et de danse traditionnelle amazighe du Maroc, originaire de la région du Haut-Atlas. C'est une tradition culturelle qui est pratiquée principalement lors de célébrations, comme les mariages, les fêtes religieuses ou les festivals locaux.",
  musique_andalouse : "Originaire d'Andalousie, en Espagne, la musique andalouse a été introduite au Maroc au 15ème siècle. Elle est souvent jouée lors de cérémonies religieuses et est caractérisée par des mélodies complexes et des paroles poétiques en arabe classique.",
  musique_raï : "Originaire d'Algérie, la musique raï est également populaire au Maroc. Elle est souvent jouée lors de fêtes et de mariages et est caractérisée par des paroles en arabe dialectal et des rythmes entraînants.",
  musique_moderne : "La musique pop et rock moderne est également populaire au Maroc, avec de nombreux artistes locaux émergents dans ces genres musicaux. Des festivals de musique modernes ont lieu dans tout le pays, attirant des artistes et des fans de musique du monde entier.",
  musique_de_région_Orientale : "Cette musique est originaire de la région de l'Oriental, qui se situe à l'est du Maroc, près de la frontière algérienne. Elle est caractérisée par des rythmes dynamiques et des mélodies traditionnelles, souvent accompagnées d'instruments comme le oud, le violon et le luth.",
  musique_aissawa : "Cette musique est originaire de la ville de Meknès, dans le centre du Maroc, et est souvent associée à des cérémonies religieuses. Elle est caractérisée par des rythmes répétitifs et des percussions intenses, ainsi que par des chants et des danses hypnotiques.",
  musique_juifs : "Les Juifs ont vécu au Maroc pendant des siècles et ont développé leur propre style de musique, qui est souvent caractérisé par des mélodies envoûtantes et des paroles en hébreu et en arabe. Les instruments utilisés incluent souvent le oud, le violon et le kanoun.",
  musique_souss : "Cette musique est originaire de la région du Souss, dans le sud du Maroc. Elle est caractérisée par des mélodies rythmées et joyeuses, souvent accompagnées d'instruments tels que le bendir, la flûte et la guembri.",
  aita : "Une musique populaire du Maroc qui est souvent associée aux Amazighs. Elle est souvent jouée lors de mariages ou de fêtes.",
  izlan : "Une musique traditionnelle originaire de la région de Souss, qui est souvent accompagnée de poésie.",
  rifia : "Une musique populaire originaire de la région de Rif, qui est influencée par les rythmes andalous.",
  reggada : "C'est une musique populaire originaire de l'est du Maroc, qui est souvent jouée lors de fêtes et de célébrations. Elle est influencée par la musique traditionnelle amazighe ainsi que par des styles plus modernes comme la musique populaire égyptienne.",
  tachelhit : "Une forme de musique traditionnelle associée aux Berbères du Sud du Maroc. Elle est souvent jouée lors de fêtes et de mariages, et est souvent accompagnée de danse.",
  ahidous : "Une musique et danse traditionnelle de la région de l'Atlas, souvent jouée lors de célébrations et de fêtes.",
  imzad : "Une musique traditionnelle associée aux Touaregs du Sud du Maroc, qui est souvent accompagnée d'un instrument de musique éponyme, l'imzad.",

  musique_gnawa_eng: "Originally from the Moroccan Sahara, Gnawa music is often associated with religious ceremonies. It is played with instruments such as the guembri, a kind of three-stringed lute, and the krakebs, metal cymbals.",
  musique_chaabi_eng: "Popular in Moroccan cities, chaâbi music is often played at weddings and festivals. It is characterized by poetic lyrics in darija, the Moroccan dialect, and is often accompanied by instruments such as the mandolin, violin, and banjo.",
  ahwach_eng: "Ahwach is a form of traditional Amazigh music and dance from the High Atlas region of Morocco. It is a cultural tradition that is mainly practiced during celebrations, such as weddings, religious festivals, or local festivals.",
  musique_andalouse_eng: "Originally from Andalusia, Spain, Andalusian music was introduced to Morocco in the 15th century. It is often played during religious ceremonies and is characterized by complex melodies and poetic lyrics in classical Arabic.",
  musique_raï_eng: "Originally from Algeria, raï music is also popular in Morocco. It is often played at festivals and weddings and is characterized by lyrics in dialectal Arabic and catchy rhythms.",
  musique_moderne_eng: "Modern pop and rock music is also popular in Morocco, with many emerging local artists in these genres. Modern music festivals take place throughout the country, attracting music artists and fans from all over the world.",
  musique_de_région_Orientale_eng: "This music originates from the Oriental region, located in the east of Morocco, near the Algerian border. It is characterized by dynamic rhythms and traditional melodies, often accompanied by instruments such as the oud, violin, and lute.",
  musique_aissawa_eng: "This music originates from the city of Meknes, in central Morocco, and is often associated with religious ceremonies. It is characterized by repetitive rhythms and intense percussion, as well as hypnotic singing and dancing.",
  musique_juifs_eng: "Jews have lived in Morocco for centuries and have developed their own style of music, which is often characterized by enchanting melodies and lyrics in Hebrew and Arabic. Instruments used often include the oud, violin, and kanoun.",
  musique_souss_eng: "This music originates from the Souss region in southern Morocco. It is characterized by lively and rhythmic melodies, often accompanied by instruments such as the bendir, flute, and guembri.",
  aita_eng: "A popular music in Morocco that is often associated with the Amazighs. It is often played at weddings or festivals.",
  izlan_eng: "A traditional music originating from the Souss region, which is often accompanied by poetry.",
  rifia_eng: "A popular music originating from the Rif region, which is influenced by Andalusian rhythms.",
  reggada_eng: "This is a popular music originating from eastern Morocco, often played at parties and celebrations. It is influenced by traditional Amazigh music as well as more modern styles such as Egyptian popular music.",
  tachelhit_eng: "A form of traditional music associated with the Berbers of southern Morocco. It is often played at festivals and weddings and is often accompanied by dance.",
  ahidous_eng: "A traditional music and dance from the Atlas region, often played at celebrations and festivals.",
  imzad_eng: "A traditional music associated with the Touaregs of southern Morocco, which is often accompanied by a musical instrument of the same name, the imzad.",

  // Personnes Historiques :
  Moulay_Ismail : "Ce sultan alaouite du XVIIe siècle a dirigé le Maroc pendant plus de 50 ans, consolidant son pouvoir et étendant son empire. Il est connu pour avoir créé une armée puissante, ainsi que pour sa construction de la ville de Meknès.",
  Mohammed_V : "Mohammed V a été un dirigeant important du Maroc pendant la période coloniale française. Il a lutté pour l'indépendance du Maroc, a été exilé en 1953, puis est revenu triomphalement en 1955 pour devenir le premier roi du Maroc indépendant.",
  Fatima_AlFihri : "Cette femme a fondé la plus ancienne université au monde encore en activité, l'Université Al-Qarawiyyin de Fès, en 859. Cette université est devenue un centre d'apprentissage et de savoir dans le monde islamique.",
  Ahmed_alMansour : "Ce sultan alaouite du XVIe siècle a gouverné le Maroc pendant une période de prospérité et de puissance, étendant son empire jusqu'au Sénégal et à la Mauritanie. Il est connu pour son architecture et ses réalisations culturelles.",
  Averroès : "Également connu sous le nom d'Ibn Rushd, Averroès était un philosophe, médecin et juriste andalou du XIIe siècle qui a joué un rôle important dans la transmission des idées grecques en Europe occidentale. Il a également été un important commentateur des œuvres d'Aristote.",
  Moulay_Ali_Cherif : "Ce sultan alaouite du XVIIIe siècle est considéré comme le fondateur de la dynastie alaouite actuelle, qui gouverne le Maroc depuis le XVIIe siècle.",
  Ibn_Battuta : "Né au XIVe siècle à Tanger, Ibn Battuta est considéré comme l'un des plus grands voyageurs et explorateurs de tous les temps. Il a parcouru plus de 120 000 kilomètres, visitant de nombreux pays et régions du monde, et a laissé derrière lui des récits de ses voyages qui sont encore étudiés aujourd'hui.",
  Moulay_Abdallah : "Ce sultan alaouite du XIXe siècle a introduit de nombreuses réformes au Maroc, notamment en matière d'éducation, de justice et de diplomatie. Il a également travaillé à moderniser l'armée marocaine et à renforcer les relations avec les puissances européennes.",
  Tahar_Ben_Jelloun : "Né en 1944 à Fès, Tahar Ben Jelloun est un écrivain et intellectuel marocain connu pour ses écrits sur la culture et la société marocaines, ainsi que pour son engagement en faveur des droits de l'homme. Il a remporté de nombreux prix pour son travail, notamment le prix Goncourt en 1987.",
  Mohamed_Choukri : "Né en 1935 à Tanger, Mohamed Choukri est un écrivain marocain connu pour son roman autobiographique, qui raconte son enfance difficile et sa vie dans les rues de Tanger. Son travail a été traduit dans de nombreuses langues et a eu une influence importante sur la littérature marocaine moderne.",
  Ahmed_Baba : "Né au XVIe siècle à Tombouctou, Ahmed Baba était un érudit musulman, un poète et un historien marocain qui a écrit de nombreux ouvrages sur la culture et la société africaines. Il a été emprisonné par les autorités marocaines pour ses opinions politiques et religieuses, mais a finalement été libéré et est devenu un conseiller de la cour royale.",
  Abderrahmane_El_Youssoufi : "Né en 1924 à Tanger, Abderrahmane El Youssoufi était un avocat, un homme politique et un militant pour les droits de l'homme qui a dirigé le gouvernement marocain de 1998 à 2002. Il a travaillé à promouvoir la démocratie et les réformes politiques au Maroc, et a été salué pour son engagement en faveur de la paix et de la justice.",
  Fatima_Mernissi : "Née en 1940 à Fès, Fatima Mernissi était une écrivaine, une sociologue et une féministe marocaine qui a écrit de nombreux ouvrages sur la condition des femmes dans la société musulmane. Elle a travaillé à sensibiliser les Marocains et les musulmans du monde entier aux droits des femmes et à leur émancipation, et a reçu de nombreux prix pour son travail.",
  Abdellatif_Laâbi : "Né en 1942 à Fès, Abdellatif Laâbi est un poète, un écrivain et un militant politique marocain qui a été emprisonné pendant huit ans pour son opposition au régime du roi Hassan II. Il a continué à écrire et à militer pour la démocratie et les droits de l'homme, et a reçu de nombreux prix pour son travail.",
  Lalla_Aicha : "Née en 1930 à Rabat, Lalla Aicha était la sœur du roi Hassan II et une championne de golf marocaine renommée. Elle a remporté de nombreux titres de golf internationaux dans les années 1950 et 1960, et a travaillé à promouvoir le sport et le tourisme au Maroc. Elle est également connue pour son travail en faveur de l'éducation et des droits des femmes.",

  Moulay_Ismail_eng: "This Alawite sultan of the 17th century ruled Morocco for more than 50 years, consolidating his power and expanding his empire. He is known for creating a powerful army, as well as for his construction of the city of Meknes.",
  Mohammed_V_eng: "Mohammed V was an important leader of Morocco during the French colonial period. He fought for Morocco's independence, was exiled in 1953, then returned triumphantly in 1955 to become the first king of independent Morocco.",
  Fatima_AlFihri_eng: "This woman founded the world's oldest continuously operating university, Al-Qarawiyyin University of Fez, in 859. This university has become a center of learning and knowledge in the Islamic world.",
  Ahmed_alMansour_eng: "This Alawite sultan of the 16th century ruled Morocco during a period of prosperity and power, expanding his empire to Senegal and Mauritania. He is known for his architecture and cultural achievements.",
  Averroès_eng: "Also known as Ibn Rushd, Averroes was a 12th-century Andalusian philosopher, physician, and jurist who played an important role in transmitting Greek ideas to Western Europe. He was also an important commentator on the works of Aristotle.",
  Moulay_Ali_Cherif_eng: "This Alawite sultan of the 18th century is considered the founder of the current Alawite dynasty, which has ruled Morocco since the 17th century.",
  Ibn_Battuta_eng: "Born in the 14th century in Tangier, Ibn Battuta is considered one of the greatest travelers and explorers of all time. He traveled more than 120,000 kilometers, visiting many countries and regions of the world, and left behind accounts of his travels that are still studied today.",
  Moulay_Abdallah_eng: "This Alawite sultan of the 19th century introduced many reforms in Morocco, particularly in education, justice, and diplomacy. He also worked to modernize the Moroccan army and strengthen relations with European powers.",
  Tahar_Ben_Jelloun_eng: "Born in 1944 in Fez, Tahar Ben Jelloun is a Moroccan writer and intellectual known for his writings on Moroccan culture and society, as well as for his commitment to human rights. He has won many awards for his work, including the Prix Goncourt in 1987.",
  Mohamed_Choukri_eng: "Born in 1935 in Tangier, Mohamed Choukri is a Moroccan writer known for his autobiographical novel, which tells of his difficult childhood and life on the streets of Tangier. His work has been translated into many languages and has had a significant influence on modern Moroccan literature.",
  Ahmed_Baba_eng: "Born in the 16th century in Timbuktu, Ahmed Baba was a Muslim scholar, poet, and historian from Morocco who wrote many works on African culture and society. He was imprisoned by Moroccan authorities for his political and religious views but was eventually released and became an adviser to the royal court.",
  Abderrahmane_El_Youssoufi_eng: "Born in 1924 in Tangier, Abderrahmane El Youssoufi was a lawyer, politician, and human rights activist who led the Moroccan government from 1998 to 2002. He worked to promote democracy and political reforms in Morocco and was praised for his commitment to peace and justice.",

  // Produits Cosmétiques :
  argan : "Cette huile est extraite des noix d'arganier, un arbre originaire du Maroc. L'huile d'argan est riche en vitamine E, en acides gras essentiels et en antioxydants. Elle est souvent utilisée pour hydrater la peau et les cheveux, ainsi que pour traiter les vergetures et les cicatrices.",
  ghassoul : "Aussi connu sous le nom de rhassoul, le ghassoul est une argile naturelle extraite des montagnes de l'Atlas au Maroc. Cette argile est souvent utilisée comme masque facial pour nettoyer en profondeur la peau et éliminer les impuretés.",
  eau_de_rose : "L'eau de rose est obtenue en distillant des pétales de roses. Elle est souvent utilisée comme tonique pour la peau, car elle a des propriétés apaisantes et hydratantes.",
  henné : "Le henné est une plante qui produit une teinture naturelle rouge ou brune utilisée pour la coloration des cheveux et la décoration de la peau. Au Maroc, le henné est souvent utilisé pour les célébrations et les mariages.",
  savon_noir : "Le savon noir est fabriqué à partir d'huile d'olive et d'olives noires broyées. Il est souvent utilisé pour exfolier la peau et la rendre plus douce.",
  kajal : "Le kajal est un eye-liner traditionnel utilisé pour intensifier le regard. Il est fait à partir d'ingrédients naturels comme le charbon, le beurre de karité et l'huile d'olive.",
  rose_Damas : "Les pétales de cette fleur sont utilisés pour produire de l'eau de rose, qui est utilisée dans de nombreux produits de beauté pour ses propriétés apaisantes et rafraîchissantes pour la peau.",

  argan_eng: "This oil is extracted from the nuts of the argan tree, which is native to Morocco. Argan oil is rich in vitamin E, essential fatty acids, and antioxidants. It is often used to moisturize the skin and hair, as well as to treat stretch marks and scars.",
  ghassoul_eng: "Also known as rhassoul, ghassoul is a natural clay extracted from the Atlas Mountains in Morocco. This clay is often used as a facial mask to deeply cleanse the skin and remove impurities.",
  eau_de_rose_eng: "Rose water is obtained by distilling rose petals. It is often used as a tonic for the skin, as it has soothing and moisturizing properties.",
  henné_eng: "Henna is a plant that produces a natural red or brown dye used for hair coloring and skin decoration. In Morocco, henna is often used for celebrations and weddings.",
  savon_noir_eng: "Black soap is made from olive oil and crushed black olives. It is often used to exfoliate the skin and make it softer.",
  kajal_eng: "Kajal is a traditional eyeliner used to intensify the look. It is made from natural ingredients such as charcoal, shea butter, and olive oil.",
  rose_Damas_eng: "The petals of this flower are used to produce rose water, which is used in many beauty products for its soothing and refreshing properties for the skin.",
  
  // Places à visiter :
  Jemaa_el_Fna : "C'est l'une des places les plus célèbres du Maroc et une attraction touristique populaire. Elle est connue pour ses stands de nourriture, ses musiciens, ses danseurs, ses conteurs et ses charmeurs de serpents.",
  Place_Mohammed_V: "Cette place est située dans le centre-ville de Rabat et est entourée de nombreux bâtiments gouvernementaux importants, y compris le palais royal.",
  Place_Moulay_Hassan : "ette place se trouve au cœur de la ville portuaire d'Essaouira et est entourée de nombreux restaurants, cafés et magasins.",
  Ruines_romaines_de_Volubilis : "Ces ruines situées dans le nord-ouest du Maroc témoignent de l'importance de la civilisation romaine dans la région, avec des vestiges de bains, de temples et de maisons.",
  Kasbah_Ait_Benhaddou : "Cette forteresse située sur la route entre Marrakech et le désert est un exemple remarquable de l'architecture en terre du Maroc.",
  Porte_Bab_Mansour : "Cette porte monumentale située à Meknès est un exemple remarquable de l'architecture islamique, avec des décorations en céramique et en marbre.",
  Tombeaux_saadiens : "Situés à Marrakech, ces tombeaux datent du 16ème siècle et sont remarquables pour leur architecture et leur décoration en mosaïque.",
  Tour_Hassan : "Cette tour située à Rabat était initialement prévue pour être la plus grande mosquée du monde, mais elle n'a jamais été terminée en raison de la mort du sultan qui l'a initiée. Aujourd'hui, elle est un monument historique emblématique de la ville.",
  Place_Outa_elHammam : "Cette place est située dans la ville bleue de Chefchaouen et est entourée de bâtiments peints en bleu et blanc, ainsi que de nombreux magasins, restaurants et cafés.",

  Jemaa_el_Fna_eng: "This is one of the most famous squares in Morocco and a popular tourist attraction. It is known for its food stalls, musicians, dancers, storytellers, and snake charmers.",
  Place_Mohammed_V_eng: "This square is located in the city center of Rabat and is surrounded by many important government buildings, including the royal palace.",
  Place_Moulay_Hassan_eng: "This square is located in the heart of the port city of Essaouira and is surrounded by many restaurants, cafes, and shops.",
  Ruines_romaines_de_Volubilis_eng: "These ruins located in northwest Morocco testify to the importance of Roman civilization in the region, with remains of baths, temples, and houses.",
  Kasbah_Ait_Benhaddou_eng: "This fortress located on the road between Marrakech and the desert is a remarkable example of Morocco's earthen architecture.",
  Porte_Bab_Mansour_eng: "This monumental gate located in Meknes is a remarkable example of Islamic architecture, with decorations in ceramic and marble.",
  Tombeaux_saadiens_eng: "Located in Marrakech, these tombs date back to the 16th century and are remarkable for their architecture and mosaic decoration.",
  Tour_Hassan_eng: "This tower located in Rabat was initially intended to be the largest mosque in the world, but it was never completed due to the death of the sultan who initiated it. Today, it is an iconic historical monument of the city.",
  Place_Outa_elHammam_eng: "This square is located in the blue city of Chefchaouen and is surrounded by buildings painted in blue and white, as well as many shops, restaurants, and cafes.",

  // Outils de Cuisine
  Le_tagine : "Le tagine est un plat de cuisson en terre cuite, avec un couvercle conique qui permet de conserver les saveurs et les arômes des ingrédients. Il est utilisé pour préparer des plats mijotés tels que le tagine de poulet aux olives ou le tagine de légumes.",
  couscoussier : "Le couscoussier est un ustensile de cuisine composé de deux parties : une grande marmite pour faire cuire le couscous, et une passoire pour la vapeur qui permet de cuire les légumes et la viande qui accompagneront le couscous.",
  couteau : "Le couteau de cuisine est un outil essentiel pour préparer les ingrédients pour les plats marocains.",
  tamis : "Le tamis est utilisé pour filtrer les ingrédients de cuisson tels que la farine, le sucre et les épices.",
  cendrier : " Le cendrier en terre cuite est souvent utilisé pour la cuisson au charbon de bois, comme pour les brochettes de viande ou les grillades.",
  cuit_vapeur : "Le cuit-vapeur est un outil qui permet de cuire à la vapeur les légumes, la viande et le poisson, ce qui est une méthode de cuisson courante dans la cuisine marocaine.",
  houf : "Le houf est un grand plat en terre cuite, souvent utilisé pour servir les tajines et les plats mijotés.",
  moule : "Les moules à pâtisserie sont utilisés pour préparer des desserts tels que les cornes de gazelle et les ghribas, qui sont des spécialités marocaines.",

  tagine_eng: "The tagine is a clay cooking dish, with a conical lid that helps to preserve the flavors and aromas of the ingredients. It is used to prepare simmered dishes such as chicken tagine with olives or vegetable tagine.",
  couscoussier_eng: "The couscoussier is a kitchen utensil composed of two parts: a large pot for cooking the couscous, and a strainer for the steam that cooks the vegetables and meat that will accompany the couscous.",
  couteau_eng: "The kitchen knife is an essential tool for preparing ingredients for Moroccan dishes.",
  tamis_eng: "The sieve is used to filter cooking ingredients such as flour, sugar, and spices.",
  cendrier_eng: "The clay ashtray is often used for charcoal cooking, such as for meat skewers or grilling.",
  cuit_vapeur_eng: "The steamer is a tool that allows for steaming vegetables, meat, and fish, which is a common cooking method in Moroccan cuisine.",
  houf_eng: "The houf is a large clay dish, often used to serve tagines and simmered dishes.",
  moule_eng: "Pastry molds are used to prepare desserts such as gazelle horns and ghribas, which are Moroccan specialties.",
};



